spring.application.name=OrmDemo
spring.datasource.url=jdbc:mysql://localhost:3306/Ormdemo
spring.datasource.username=root
spring.datasource.password=root
# defins ddl -auto quree , handalling ddl commonds
#ddl - auto -'update ' for development - uses existing  table , create new if its not there  
# ddl- auto - 'none' for product - no structure change in tables allowed

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.formate_sql=true
